# Generated by Django 4.0.4 on 2022-05-31 14:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number', models.IntegerField(unique=True)),
                ('Description', ckeditor.fields.RichTextField()),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Short_Code', models.CharField(max_length=25)),
                ('Description', ckeditor.fields.RichTextField()),
                ('Base_Occupancy', models.IntegerField()),
                ('Max_Occupancy', models.IntegerField()),
                ('Extra_Bed', models.IntegerField()),
                ('Kids_Occupancy', models.IntegerField()),
                ('Amenities', models.CharField(max_length=25)),
                ('Base_Price', models.IntegerField()),
                ('Additional_Person_Price', models.IntegerField()),
                ('Extra_Bed_Price', models.IntegerField()),
            ],
        ),
    ]
