# Generated by Django 4.0.4 on 2022-05-31 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
