# Generated by Django 4.0.4 on 2022-05-31 19:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0002_alter_floor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
