# Generated by Django 4.0.4 on 2022-06-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0002_alter_room_type_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.floor')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.room_type')),
            ],
        ),
    ]
