# Generated by Django 4.0.4 on 2022-06-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0002_housekeeping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Housekeeping',
            new_name='HousekeepingStatus',
        ),
    ]
