# Generated by Django 4.0.4 on 2022-07-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0003_rename_housekeeping_housekeepingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.housekeepingstatus')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.room')),
            ],
        ),
    ]
