# Generated by Django 4.0.4 on 2022-07-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0004_housekeeping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housekeeping',
            old_name='name',
            new_name='housekeeping_status',
        ),
    ]
