# Generated by Django 4.0.4 on 2022-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0004_alter_room_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
