# Generated by Django 4.0.4 on 2022-07-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0005_rename_name_housekeeping_housekeeping_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housekeeping',
            old_name='assigned_to',
            new_name='assign_to',
        ),
    ]
