# Generated by Django 4.0.4 on 2022-07-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0006_rename_assigned_to_housekeeping_assign_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room_type',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/None/')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.imagefolder')),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.ManyToManyField(blank=True, to='hotelManagement.image'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ManyToManyField(blank=True, to='hotelManagement.image'),
        ),
        migrations.AddField(
            model_name='room_type',
            name='image',
            field=models.ManyToManyField(blank=True, to='hotelManagement.image'),
        ),
    ]
