# Generated by Django 4.0.4 on 2022-07-25 17:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotelManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0007_imagefolder_remove_amenity_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_number', models.IntegerField(unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.floor')),
            ],
        ),
        migrations.RenameModel(
            old_name='Housekeeping',
            new_name='HousekeepingForRoom',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='additional_person_price',
            new_name='additional_price_per_kid',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='kids_occupancy',
            new_name='additional_price_per_person',
        ),
        migrations.AddField(
            model_name='room_type',
            name='d0',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='room_type',
            name='d1',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='room_type',
            name='d2',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='room_type',
            name='d3',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='room_type',
            name='d4',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='room_type',
            name='d5',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='room_type',
            name='d6',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Employee/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hotelManagement.models.Image.upload_path),
        ),
        migrations.CreateModel(
            name='HousekeepingForHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.hall')),
                ('housekeeping_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.housekeepingstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Hall_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_code', models.CharField(max_length=25)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('base_occupancy', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('amenities', models.ManyToManyField(blank=True, to='hotelManagement.amenity')),
                ('image', models.ManyToManyField(blank=True, to='hotelManagement.image')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='hall_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelManagement.hall_type'),
        ),
    ]
