# Generated by Django 4.0.4 on 2022-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0008_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Employee/'),
        ),
    ]
