# Generated by Django 4.0.4 on 2022-07-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0008_hall_rename_housekeeping_housekeepingforroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_type',
            old_name='d0',
            new_name='fri',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='d1',
            new_name='mon',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='d2',
            new_name='sat',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='d3',
            new_name='sun',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='d4',
            new_name='thu',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='d5',
            new_name='two',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='d6',
            new_name='wed',
        ),
    ]
