# Generated by Django 4.0.4 on 2022-07-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0009_rename_d0_room_type_fri_rename_d1_room_type_mon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_type',
            old_name='two',
            new_name='tue',
        ),
    ]
