# Generated by Django 4.0.4 on 2022-07-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0010_rename_two_room_type_tue'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_type',
            name='fri',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall_type',
            name='mon',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall_type',
            name='sat',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall_type',
            name='sun',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall_type',
            name='thu',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall_type',
            name='tue',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall_type',
            name='wed',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
