# Generated by Django 4.0.4 on 2022-07-27 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelManagement', '0011_hall_type_fri_hall_type_mon_hall_type_sat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price_type', models.CharField(choices=[('Per Person', 'Per Person'), ('Per Night', 'Per Night'), ('Fixed Price', 'Fixed Price')], max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('active', models.BooleanField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
